services:
  - type: web
    name: smart-inverter-api
    runtime: node
    rootDir: iot-backend
    buildCommand: npm install
    startCommand: node app.js
    plan: free
    envVars:
      - key: INFLUX_URL
        sync: false
      - key: INFLUX_TOKEN
        sync: false
      - key: INFLUX_ORG
        sync: false
      - key: INFLUX_BUCKET
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: PORT
        value: 3000
